package com.github.jelf.xml;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.HashMap;

/**
 * Created by jelf on 29.09.2014.
 */
public class HashMapTag extends SimpleTagAcceptor {

    public String name;
    public HashMap<String,String> params;
    public ArrayList<HashMapTag> nested;
    public String value;

    private static HashMapFactory factory = new HashMapFactory();

    /**
     * Tags shouldn't have any information about it's factory, but this will
     * @return HashMapFactory object, which could be used in XmlParser
     */
    public static @NotNull HashMapFactory getFactory() {
        return factory;
    }

    /**
     * Generates a new tag in case you need to insert it somewhere or in factory
     * @param name any name is possible, HashMapFactory generates HashMapTag in any case
     */
    public HashMapTag(@NotNull String name) {
        this.name = name;
        params = new HashMap<String, String>();
        nested = new ArrayList<HashMapTag>();
        value = null;
    }

    /**
     * Adds param to a nested map
     * @param name parameter name
     * @param value parameter value
     */
    @Override
    public void addParam(@NotNull String name, @Nullable String value) {
        params.put(name, value);
    }

    /**
     * Simply sets value of nested string
     * @param value tag body without any spaces in start or end
     */
    @Override
    public void setValue(@Nullable String value) {
        this.value=value;
    }

    /**
     * Adds tag to a nested map
     * @param nested the tag, generated by a TagAcceptorFactory
     */
    @Override
    public void addNested(@NotNull TagAcceptor nested) {
        this.nested.add((HashMapTag) nested);
    }
}
